import praw
import openai
import re
import datetime
import random

# Reddit API credentials
reddit = praw.Reddit(
    client_id='<YOUR_CLIENT_ID>',
    client_secret='<YOUR_CLIENT_SECRET>',
    username='<YOUR_USERNAME>',
    password='<YOUR_PASSWORD>',
    user_agent='com.gabriel-sykes.askgpt3:v1.0'
)

# OpenAI API credentials
openai.api_key = '<YOUR_API_KEY>'

# Set subreddit for post search
subreddit = 'askreddit'

# Get top post from r/askreddit in last 24 hours
posts = reddit.subreddit(subreddit).top('day', limit=1)
random_post = random.choice([post for post in posts])

# Display title of selected post and link to post
print(f"{random_post.title}\n{random_post.url}")

# Combine post title and body for GPT-3 input
post_text = random_post.title + " " + random_post.selftext

# Preprocess post text for GPT-3 input
post_text = re.sub('\n', ' ', post_text)
post_text = re.sub('\[(.*?)\]', '', post_text)
post_text = re.sub('www.(.*?)\s', '', post_text)

# Generate comment with GPT-3
prompt = f"Please write a comment for the following post:\n{post_text}"
response = openai.Completion.create(
    engine='text-davinci-003',
    prompt=prompt,
    temperature=1.0,
    max_tokens=1024,
    n=1,
    stop=None,
    timeout=60,
)

# Print generated comment
generated_comment = response.choices[0].text.strip()
print(generated_comment)

# Comment on post with generated comment and disclaimer
disclaimer = ("\n\n---\n^(This comment was generated by a bot using OpenAI's GPT-3 language model as part of an experiment with coding. The opinions expressed in this comment are not necessarily representative of the views of the bot's creator, or the owner of the account this was posted on.)")
comment = generated_comment + disclaimer

try:
    random_post.reply(comment)
    print("Comment posted successfully!")
except Exception as e:
    print("Error posting comment:", e)
